# ${project.name} - ${project.description}
# 项目地址: ${project.url}
# 下载地址: ${project.distributionManagement.downloadUrl}
version: ${project.version}

debug: false

sounds:
  not-permitted: ENTITY_ITEM_PICKUP # 未经允许进入区域时播放的声音

regions:
